sudo: required
services:
  - docker

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    
jobs:
  include:
    - stage: before_install
      script: bash ./pipeline_scripts/before_install.sh
    - stage: build_image
      script: 
        - docker build -t antonijaa/service1:test -f ./service1/Dockerfile ./service1
        - docker build -t antonijaa/service2:test -f ./service2/Dockerfile ./service2
    - stage: unit_tests
      script: echo "skiping unit testing"
    - stage: integration_tests
      script: echo "skiping integration testing"
    - stage: push_arifact
      script: bash ./pipeline_scripts/push_artifact.sh
    - stage: deploy_to_staging
      script: skip
      deploy: 
        provider: script
        script: bash ./pipeline_scripts/deploy_to_staging.sh
        on:
          branch: master          
    - stage: smoke_test
      script: bash ./pipeline_scripts/smoke_test.sh
    - stage: e2e_tests
      script: echo "skiping e2e testing"
    - stage: deploy_to_production
      script: skip
      deploy: 
        provider: script
        script: bash ./pipeline_scripts/deploy_to_production.sh
        on:
          branch: master
