sudo: required
services:
  - docker

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

before_install:
  - chmod +x ./pipeline_scripts/deploy_to_production.sh
  - chmod +x  ./pipeline_scripts/before_install.sh
jobs:
  include:
    - stage: build_and_test
      script:
        - ./pipeline_scripts/before_install.sh
        - ./pipeline_scripts/deploy_to_production.sh
        - echo "skiping unit testing"
        - echo "skiping integration testing"
