sudo: required
services:
  - docker

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    
jobs:
  include:
    - stage: build_and_test
      script: 
        - docker build -t antonijaa/service1:test -f ./service1/Dockerfile ./service1
        - docker build -t antonijaa/service2:test -f ./service2/Dockerfile ./service2
        - echo "skiping unit testing"
        - echo "skiping integration testing"
    - stage: push_arifact
      script: bash ./pipeline_scripts/push_artifact.sh
    - stage: deploy_to_staging
      script: 
        - bash ./pipeline_scripts/before_install.sh
        - bash ./pipeline_scripts/deploy_to_staging.sh
        - bash ./pipeline_scripts/smoke_test.sh
        - echo "skiping e2e testing"
      if: branch = master 
    - stage: deploy_to_production
      script: 
        - bash ./pipeline_scripts/before_install.sh
        - bash ./pipeline_scripts/deploy_to_production.sh
      if: branch = master 
