version: '3'
services:
  service1:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./service1
    ports:
      - '5001:8080'
    volumes:
      - ./service1:/usr/app
  service2:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure
    build: ./service2
    environment:
      - SERVIS1_HOST=service1
      - SERVIS1_PORT=8080
    ports:
      - '5002:8080'
    volumes:
      - ./service2:/usr/app

